### ISSUE TITLE
Unable to uninstall the extension

### ISSUE THREAD

**Issue by Rodenastyle** [flagrow/masquerade#14]
PHP Version 7.0.15

I'm reproducing it by simply uninstalling the extension.

Logs thrown:
`
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Flarum\\Extension\\ExtensionManager::migrateDown() must be an instance of Flarum\\Extension\\Extension, null given, called in ExtensionManager.php on line 171 and defined in ExtensionManager.php:250
Stack trace:
#0 ExtensionManager.php(171): Flarum\\Extension\\ExtensionManager->migrateDown(NULL)
#1 UninstallExtensionController.php(44): Flarum\\Extension\\ExtensionManager->uninstall(Object(Flarum\\Extension\\Extension))
#2 AbstractDeleteController.php(25): Flarum\\Api\\Controller\\UninstallExtensionControll in ExtensionManager.php on line 250
`

**Comment by clarkwinkelmann** [comment]
Did we discuss this issue via another channel ? I'm really sorry if we've forgotten you :scream: 

Are you still experiencing the issue ? Was it via Bazaar or the default extension page ?

**Comment by clarkwinkelmann** [comment]
I'm closing this. Feel free to reopen if it happens again and/or you have more details about it :wink:
