### ISSUE TITLE
Admin/ site owner cannot see conversations they are not a party to

### ISSUE THREAD

**Issue by bikepost** [flagrow/masquerade#15]
Thank you for making this. 
It addresses the #1 complaint from my forum members: "no PM function".

As a site owner, I would want the ability to see all private conversations (read only: without editing capability is fine).
Please consider that a site owner is responsible (and probably legally liable) for what goes on in their forum.

**Comment by luceos** [comment]
I guess you mistake this repository for https://github.com/flagrow/byobu ; I can imagine you would like to have this feature. I would consider such a feature (toggle in admin for instance) but only if we make this somehow clear. Feel free to create a new issue with a possible (non technical) implementation on the correct repository.
