### ISSUE TITLE
mutate answer values based on validation rules

### ISSUE THREAD

**Issue by luceos** [flagrow/masquerade#4]
Some fields can be shown different based on their validation rules, eg:

- url (can point to specific files too)
- phone
- timezone
- ip (not too important)

**Comment by AngellitoX** [comment]
Regarding validation rules, I just updated to 0.1.0-beta.3.2, and rules seem not to be working for me. I just put "url" without the quotation marks, and put a single number on the configured field, and it didn't forbid me to place a number with the URL rule. I have tested a few others like "string" too.

**Comment by clarkwinkelmann** [comment]
I'm closing this as it was kind of implemented in 0.1 and in 0.2 we now have the field types which have an edit and display template for each type
