### ISSUE TITLE
Composite key for field answer should be unique

### ISSUE THREAD

**Issue by clarkwinkelmann** [flagrow/masquerade#8]
Didn't cause any issue (yet) but I noticed that in the database.

https://github.com/flagrow/masquerade/blob/master/migrations/2017_05_15_flagrow_answers_table.php#L15

    $table->index(['id', 'field_id', 'user_id']);

should probably be

    $table->unique(['id', 'field_id', 'user_id']);

**Comment by luceos** [comment]
```
$table->unique(['field_id', 'user_id']);
```

Good point.

**Comment by Rodenastyle** [comment]
Testing a new migration file for this noticed a new issue unistalling the extension. Will report with details so you can reproduce it.

**Comment by clarkwinkelmann** [comment]
Just noticed things are a lot worse. There are no individual indexes on these fields.

A compound index is only useful if fields are queried in the order they are defined in the index. Because we query directly for the `user_id` key, it's really like there is no index at all on this column :zipper_mouth_face:
