### ISSUE TITLE
Created at and updated at timestamps are never updated

### ISSUE THREAD

**Issue by clarkwinkelmann** [flagrow/masquerade#9]
In the `flagrow_masquerade_fields` as well as `flagrow_masquerade_answers` table, `created_at` and `updated_at` stay at value `0000-00-00 00:00:00` all the time.

Maybe we don't need these values, but if they are in the table it would be nice to keep them updated.

**Comment by luceos** [comment]
Oh Flarums' AbstractModel disables timestamps per default.. 😱
